---
title: "Assign2"
author: "Yue Wang"
date: '2018-11-02'
output: html_document
---

**Q2**
```{r}
Data = read.csv("/Users/yuewang/Desktop/eXpress_dm_counts.csv",header = T, row.names = 1,sep=',')
rna_counts = function(x, y = TRUE ){  #y==FALSE means using log2
  if (y == TRUE) {
    a <- mean(Data[,x])
  } else {
    Data = Data+0.000001
    a <- mean(log2(Data[,x]))
  }
  return(a)
}
rna_counts('F101_lg_female_hdhorn')
```
**Q3**

```{r}
sample <- colnames(Data)
elements <- c()
for(i in sample){
  elements <- c(elements, rna_counts(i))
}
names(elements)=sample
```


**Q4**
```{r}
system.time(sapply(sample,rna_counts))
system.time(for(i in sample){ elements <- c(elements, rna_counts(i))})
```
**Q5**
```{r}
sapply(Data,mean)
```

**Q6**
```{r}
row_mean = function(x, y = TRUE ){  #y==FALSE means using log2
  if (y == TRUE) {
    a <- rowMeans(Data[x,])
  } else {
    Data = Data+0.000001
    a <- rowMeans(log2(Data[x,]))
  }
  return(a)
}
row_mean('FBpp0087248',TRUE)
row_mean_con=sapply(rownames(Data),row_mean)
```

**Q7**
```{r}
row_mean_male = function(x, y = TRUE,z ){  #y==FALSE means using log2
  if (y == TRUE) {
    a <- rowMeans(z[x,])
  } else {
    z = z+0.000001
    a <- rowMeans(log2(z[x,]))
  }
  return(a)
}
male_hdhorn_lg_data = Data[,grep("M.*lg_male_hdhorn",sample,value = T)]
male_hdhorn_sm_data = Data[,grep("M.*sm_male_hdhorn",sample,value = T)]
lg_mean <- sapply(rownames(Data), z=male_hdhorn_lg_data,row_mean_male)
sm_mean <- sapply(rownames(Data),z=male_hdhorn_sm_data, row_mean_male)
mean_differece = lg_mean-sm_mean
```
**Q8**
```{r}
mean = sapply(rownames(Data),row_mean)
log_mean = sapply(rownames(Data),y=FALSE,row_mean)
library(ggplot2)
ggplot(Data,aes(x=mean,y=mean_differece))+geom_point()
ggplot(Data,aes(x=log_mean,y=mean_differece))+geom_point()
```



